Made home work order model
SergeyGordeychuk/online-book-store pull request #21
Opened 2024-04-17 13:23 UTC by SergeyGordeychuk

2024-04-17 17:48 UTC, kerrrusha requested changes

2024-04-17 17:48 UTC, kerrrusha commented on src/main/java/onlinebookstore/model/Order.java
> +    @Column(name = "is_deleted", nullable = false)
1. this changes nothing
2. are you sure that for relation OneToMany at the OrderItems we should create column at the parent Order entity? i dont think so
```suggestion
    @Column(nullable = false, columnDefinition = "varchar")
    private Status status;
    @Column(nullable = false)
    private BigDecimal total;
    @Column(nullable = false)
    @DateTimeFormat(pattern = "yyyy-MM-dd'T'HH:mm:ss")
    private LocalDateTime orderDate;
    @Column(nullable = false)
    private String shippingAddress;
    @OneToMany(mappedBy = "order", cascade = CascadeType.ALL, orphanRemoval = true)
    private Set<OrderItem> orderItems = new HashSet<>();
    @Column(nullable = false)
```

2024-04-17 17:48 UTC, kerrrusha commented on src/main/java/onlinebookstore/service/order/OrderServiceImpl.java
> +    private final LocalDateTime DATE_TIME = LocalDateTime.now();
this will be invalid, because we will get old date. create that right in method
```suggestion
```

2024-04-18 07:08 UTC, MAMentorFX requested changes

2024-04-18 07:08 UTC, MAMentorFX commented on src/main/java/onlinebookstore/mapper/OrderMapper.java
> +    @Mapping(target = "orderItems", source = "orderItems")
```suggestion

```

2024-04-18 07:08 UTC, MAMentorFX commented on src/main/java/onlinebookstore/model/Order.java
> +@Where(clause = "is_deleted=false")
@Where is deprecated, use @SqlRestriction

2024-04-18 07:08 UTC, MAMentorFX commented on src/main/java/onlinebookstore/service/order/OrderServiceImpl.java
> +                .collect(Collectors.toSet());
Mapstruct supports mapping collections from the box

2024-04-18 07:08 UTC, MAMentorFX commented on src/main/java/onlinebookstore/service/order/OrderServiceImpl.java
> +        order.setTotal(total);
Use Mapstruct

2024-04-18 07:08 UTC, MAMentorFX commented on src/main/java/onlinebookstore/service/order/OrderServiceImpl.java
> +        return orderMapper.toDto(orderRepository.save(order));
Why did you save order twice?

2024-04-18 07:08 UTC, MAMentorFX commented on src/main/java/onlinebookstore/service/order/OrderServiceImpl.java
> +                .peek(oi -> oi.setOrder(order)).collect(Collectors.toSet());
```suggestion
                .peek(orderItem -> oi.setOrder(order)).collect(Collectors.toSet());

```

2024-04-18 07:08 UTC, MAMentorFX commented on src/main/java/onlinebookstore/service/order/OrderServiceImpl.java
> +                .peek(oi -> oi.setOrder(order)).collect(Collectors.toSet());
Also learn what is peek. It doesnt change the Stream. So Set<OrderItem> orderItemSet won't have order set. Use forEach instead.

2024-04-20 10:47 UTC, olekskov approved these changes

2024-04-20 10:47 UTC, olekskov commented on src/main/java/onlinebookstore/service/orderitem/OrderItemServiceImpl.java
> +                .filter(oi -> Objects.equals(oi.getId(), itemId))
```suggestion
                .filter(orderItem -> Objects.equals(orderItem.getId(), itemId))

```

2024-04-23 15:08 UTC, merged