Created tests for book and category
SergeyGordeychuk/online-book-store pull request #24
Opened 2024-05-01 07:53 UTC by SergeyGordeychuk

2024-05-01 13:36 UTC, MentorMA requested changes

2024-05-01 13:36 UTC, MentorMA commented on src/test/java/onlinebookstore/config/CustomMySqlContainer.java
> +    private static CustomMySqlContainer mysqlContainer;
You don`t need empty line between fields

2024-05-01 13:36 UTC, MentorMA commented on src/test/java/onlinebookstore/controller/BookControllerTest.java
> +                    new ClassPathResource("database/book/add-three-books-to-books-with-categories-table.sql"));
Save string to constant

2024-05-01 13:36 UTC, MentorMA commented on src/test/java/onlinebookstore/repository/book/BookRepositoryTest.java
> +
```suggestion
```

2024-05-01 13:36 UTC, MentorMA commented on src/test/java/onlinebookstore/repository/book/BookRepositoryTest.java
> +
Redundant empty line

2024-05-02 07:47 UTC, Elena-Bruyako approved these changes

2024-05-02 07:47 UTC, Elena-Bruyako commented on src/test/java/onlinebookstore/controller/BookControllerTest.java
> +        Assertions.assertEquals(3, bookDtos.length);
For the future, use static import

2024-05-02 07:47 UTC, Elena-Bruyako commented on src/test/java/onlinebookstore/service/category/CategoryServiceImplTest.java
> +            Save catgory
```suggestion
            Save category

```

2026-04-27 16:55 UTC, closed without merging